### ISSUE TITLE
Stop Rerendering until mouse hover

### ISSUE THREAD

**Issue by CaiIsProgrammer** [ValentinH/react-easy-sort#35] opened 2023-05-11 00:10 UTC
**Is your feature request related to a problem? Please describe.**

Stop Rerendering until mouse hover. im trying to render three.js components but it keeps rerendering them and creating new ones and causing a memory leak as well as not letting the threejs component actually animate for more than a second.

**Describe the solution you'd like**

i would like a variable to stop the rerender until the components are hovered

**Describe alternatives you've considered**

**Additional context**

https://gyazo.com/f0fe69eaf9791bb71b83f6563cccc8d1

- If you have ideas how to implement your new feature, please share!

- If you know any examples online that already implement such functionality, please share a link.

**Comment by ValentinH** [comment] 2023-05-11 03:53
Please provide a codesandbox showing the issue or I'll be not be able to diagnose the root cause. Having so many rendering doesn't feel right indeed.

**Comment by ValentinH** [comment] 2023-09-26 08:01
Closing as there was no answer for a while. Comment to re-open 😉

**Closed by ValentinH** 2023-09-26 08:01 UTC
